name: Selenium Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Python dependencies
        run: python -m pip install behave chromedriver_py selenium
      #- name: Run tests
      #  run: behave
